version: '3.8'

services:
  # 1. DATABASE
  db:
    image: postgis/postgis:16-3.4
    container_name: greenconnect-db-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supercalifragilisticexpialidocious
      POSTGRES_DB: GreenConnectDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  # 2. API SERVICE
  greenconnect-api:
    container_name: greenconnect-api-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production 
      EnableHttpsRedirect: "false"       
      DatabaseConnection__DefaultConnection__DbHost: db
      DatabaseConnection__DefaultConnection__DbPort: 5432
      DatabaseConnection__DefaultConnection__DbUser: postgres
      DatabaseConnection__DefaultConnection__DbPass: "supercalifragilisticexpialidocious"
      DatabaseConnection__DefaultConnection__Database: GreenConnectDb
    volumes:
      - ./GreenConnectPlatform.Api/Configs/firebase-service-account.json:/app/Configs/firebase-service-account.json
    depends_on:
      - db
    restart: unless-stopped

  # 3. WEB SERVICE
  greenconnect-web:
    container_name: greenconnect-web-container
    build:
      context: ../GreenConnectWeb 
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=https://api.green-connect.business365.vn
      - PORT=3000
    depends_on:
      - greenconnect-api
    restart: always

  # 4. NGINX PROXY
  nginx:
    image: nginx:alpine
    container_name: greenconnect-nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - greenconnect-api
      - greenconnect-web
    restart: always

volumes:
  postgres_data: