version: '3.8'

services:
  greenconnect-api:
    container_name: greenconnect-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      DatabaseConnection__DefaultConnection__DbHost: host.docker.internal
      
      DatabaseConnection__DefaultConnection__DbUser: postgres
      DatabaseConnection__DefaultConnection__DbPass: "password"
      DatabaseConnection__DefaultConnection__Database: GreenConnectDb
      DatabaseConnection__DefaultConnection__DbPort: 5432
    restart: unless-stopped
  
  nginx:
    image: nginx:alpine
    container_name: greenconnect-nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - greenconnect-api
    restart: always